### ISSUE TITLE
Add the openconfig / IETF mapping tool to the main page

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/web_root#1]

**Comment by evyncke** [comment]
AFAIK this is an extension to PYANG. Beside a pointer to the PYANG githug + Miroslav's new module, what should we do?

To be done next year after IETF transition ?

**Comment by SlavomirMazurPantheon** [comment]
Hello all,
since this repository will be closed soon I want to ask whether this issue is still relevant.
If so, can you please describe it in more details?

Regards,
Slavomír Mazúr
